### ISSUE TITLE
Error running truffle test: "Cannot find module '@digix/truffle-lightwallet-provider'"

### ISSUE THREAD

**Issue by adklempner** [transmute-industries/transmute-framework#8]
Seems like this module is missing from package.json

```
Error: Cannot find module '@digix/truffle-lightwallet-provider'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/aklempner/Repos/transmute-framework/truffle.js:1:91)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at /usr/local/lib/node_modules/truffle/node_modules/require-nocache/index.js:6:19
    at Function.Config.load (/usr/local/lib/node_modules/truffle/node_modules/truffle-config/index.js:244:23)
    at Function.Config.detect (/usr/local/lib/node_modules/truffle/node_modules/truffle-config/index.js:236:15)
    at Object.run (/usr/local/lib/node_modules/truffle/lib/commands/test.js:17:25)
    at Command.run (/usr/local/lib/node_modules/truffle/lib/command.js:74:20)
```

**Comment by OR13** [comment]
@adklempner thanks for reporting this error!

I've updated package.json https://github.com/transmute-industries/transmute-framework/commit/6a0709975c1f2392872b68f1ffafa196494d8e74
